# Generated by Django 5.1.4 on 2025-01-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='event_name',
            field=models.CharField(default='Study Fair', help_text='Name of the event', max_length=255),
        ),
    ]
