# Generated by Django 5.1.4 on 2024-12-24 07:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('quote', models.CharField(blank=True, help_text='Add an inspiring quote.', max_length=255)),
                ('why_study_here', wagtail.fields.RichTextField(blank=True, help_text='Explain why students should choose this destination.')),
                ('requirements', wagtail.fields.RichTextField(blank=True, help_text='List the requirements for studying in this destination.')),
                ('courses', wagtail.fields.RichTextField(blank=True, help_text='Provide details of popular courses in this destination.')),
                ('universities', wagtail.fields.RichTextField(blank=True, help_text='List universities in this destination.')),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Destination Page',
                'verbose_name_plural': 'Destination Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
