# Generated by Django 5.1.4 on 2024-12-26 06:48

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Add the FAQ question.', max_length=255)),
                ('answer', wagtail.fields.RichTextField(blank=True, help_text='Provide the answer to the question.')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the scholarship.', max_length=255)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Description of the scholarship.')),
            ],
        ),
        migrations.RemoveField(
            model_name='destinationpage',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='destinationpage',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='destinationpage',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='destinationpage',
            name='universities',
        ),
        migrations.RemoveField(
            model_name='destinationpage',
            name='why_study_here',
        ),
        migrations.AddField(
            model_name='destinationpage',
            name='cost_expenses',
            field=wagtail.fields.RichTextField(blank=True, help_text='Provide details of expenses.'),
        ),
        migrations.AddField(
            model_name='destinationpage',
            name='cost_range',
            field=models.CharField(blank=True, help_text='Add the estimated cost range.', max_length=255),
        ),
        migrations.AddField(
            model_name='destinationpage',
            name='short_intro',
            field=models.CharField(blank=True, help_text='Add a short introduction for the destination.', max_length=500),
        ),
        migrations.CreateModel(
            name='DestinationPageBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='Add a heading for the benefit.', max_length=255)),
                ('content', wagtail.fields.RichTextField(blank=True, help_text='Add content for the benefit.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='destination.destinationpage')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationPageRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='Add a heading for the requirement.', max_length=255)),
                ('content', wagtail.fields.RichTextField(blank=True, help_text='Add content for the requirement.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='destination.destinationpage')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationPageFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='destination.destinationpage')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='destination.faq')),
            ],
        ),
        migrations.AddField(
            model_name='destinationpage',
            name='scholarships',
            field=models.ManyToManyField(blank=True, help_text='List of available scholarships.', to='destination.scholarship'),
        ),
    ]
