# Generated by Django 5.1.4 on 2024-12-26 06:52

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_faq_scholarship_remove_destinationpage_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationpage',
            name='courses',
            field=wagtail.fields.RichTextField(blank=True, help_text='Provide details of popular courses in this destination.'),
        ),
        migrations.AddField(
            model_name='destinationpage',
            name='quote',
            field=models.CharField(blank=True, help_text='Add an inspiring quote.', max_length=255),
        ),
        migrations.AddField(
            model_name='destinationpage',
            name='universities',
            field=wagtail.fields.RichTextField(blank=True, help_text='List universities in this destination.'),
        ),
        migrations.AddField(
            model_name='destinationpage',
            name='why_study_here',
            field=wagtail.fields.RichTextField(blank=True, help_text='Explain why students should choose this destination.'),
        ),
        migrations.AlterField(
            model_name='destinationpagerequirement',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_requirements', to='destination.destinationpage'),
        ),
    ]
