# Generated by Django 5.1.4 on 2025-01-02 08:21

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0004_remove_destinationpagefaq_faq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationpage',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='destinationpage',
            name='scholarships',
        ),
        migrations.RemoveField(
            model_name='destinationpage',
            name='universities',
        ),
        migrations.CreateModel(
            name='DestinationPageCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Add the course name.', max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='destination.destinationpage')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationPageScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Add the scholarship name.', max_length=255)),
                ('details', wagtail.fields.RichTextField(blank=True, help_text='Provide additional details about the scholarship.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='destination.destinationpage')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationPageUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Add the university name.', max_length=255)),
                ('location', models.CharField(blank=True, help_text='Provide the location of the university.', max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='destination.destinationpage')),
            ],
        ),
    ]
