# Generated by Django 5.1.4 on 2025-01-07 09:48

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Blog Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DestinationIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Destination Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ScholarshipIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Scholarship Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TestIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Test Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='UniversityIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'University Index Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
