# Generated by Django 5.1.4 on 2025-01-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the category.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Add a short description of the category (optional).')),
            ],
        ),
    ]
