# Generated by Django 5.1.4 on 2025-01-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_blogcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
