# Generated by Django 5.1.4 on 2025-01-12 08:06

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('one_liner', models.CharField(blank=True, help_text='Add a one-liner about the course.', max_length=255)),
                ('field', models.CharField(blank=True, help_text='Enter the field of study.', max_length=255)),
                ('duration', models.CharField(blank=True, help_text='Specify the course duration.', max_length=255)),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Add an introduction about the course.')),
                ('key_highlights', wagtail.fields.RichTextField(blank=True, help_text='Highlight key features of the course.')),
                ('admission_details', wagtail.fields.RichTextField(blank=True, help_text='Provide details about the admission process.')),
                ('career_opportunities', wagtail.fields.RichTextField(blank=True, help_text='Explain career opportunities after this course.')),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Course Page',
                'verbose_name_plural': 'Course Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CourseFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Enter the FAQ question.', max_length=255)),
                ('answer', wagtail.fields.RichTextField(blank=True, help_text='Enter the FAQ answer.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='course.coursepage')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(help_text='Enter the field of the course.', max_length=255)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Add a description for the field.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_details', to='course.coursepage')),
            ],
        ),
        migrations.CreateModel(
            name='StudentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the student.', max_length=255)),
                ('review', wagtail.fields.RichTextField(blank=True, help_text="Add the student's review.")),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reviews', to='course.coursepage')),
            ],
        ),
    ]
