# Generated by Django 5.1.4 on 2025-01-04 09:23

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('short_intro', models.CharField(blank=True, help_text='Add a short introduction about the exam.', max_length=500)),
                ('why_take_exam', wagtail.fields.RichTextField(blank=True, help_text='Explain why students should take this exam.')),
                ('exam_types', models.CharField(blank=True, help_text='List the types of this exam.', max_length=500)),
                ('exam_format', wagtail.fields.RichTextField(blank=True, help_text='Describe the format of the exam.')),
                ('test_guide', wagtail.fields.RichTextField(blank=True, help_text='Provide a guide on how to prepare for the exam.')),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Test Page',
                'verbose_name_plural': 'Test Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TestPageComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Add the comparison title.', max_length=255)),
                ('content', wagtail.fields.RichTextField(blank=True, help_text='Provide details for the comparison.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='exam.testpage')),
            ],
        ),
        migrations.CreateModel(
            name='TestPageCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(help_text='Add the test type.', max_length=255)),
                ('cost', models.CharField(help_text='Add the cost for this test type.', max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='exam.testpage')),
            ],
        ),
        migrations.CreateModel(
            name='TestPageFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Add the FAQ question.', max_length=255)),
                ('answer', wagtail.fields.RichTextField(blank=True, help_text='Add the FAQ answer.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='exam.testpage')),
            ],
        ),
    ]
