# Generated by Django 5.1.4 on 2025-01-05 11:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpage',
            name='exam_types',
            field=wagtail.fields.RichTextField(blank=True, help_text='List the types of this exam.'),
        ),
    ]
