# Generated by Django 5.1.4 on 2024-12-25 07:46

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('writer', models.CharField(help_text='Name of the writer.', max_length=100)),
                ('post', models.CharField(help_text='Post or designation of the writer.', max_length=100)),
                ('heading', models.CharField(help_text='Heading of the blog.', max_length=255)),
                ('content', wagtail.fields.RichTextField(help_text='Main content of the blog.')),
                ('banner_image', models.ForeignKey(blank=True, help_text='Main image for the blog.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Blog Page',
                'verbose_name_plural': 'Blog Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
