# Generated by Django 5.1.4 on 2025-01-03 10:49

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='post',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='category',
            field=models.CharField(default='Uncategorized', help_text='Specify the category of the blog.', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Set the publish date for the blog.'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='summary',
            field=models.CharField(blank=True, help_text='Add a brief summary or introduction for the blog.', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='writer',
            field=models.CharField(help_text="Add the writer's name.", max_length=255),
        ),
        migrations.CreateModel(
            name='BlogPageFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Add the FAQ question.', max_length=255)),
                ('answer', wagtail.fields.RichTextField(blank=True, help_text='Add the FAQ answer.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='blog.blogpage')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='Add a heading for this section.', max_length=255)),
                ('content', wagtail.fields.RichTextField(blank=True, help_text='Add the content for this section.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blog.blogpage')),
            ],
        ),
    ]
