# Generated by Django 5.1.4 on 2025-01-10 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_blogcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='category',
        ),
    ]
