# Generated by Django 5.1.4 on 2025-01-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blogpage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='category',
            field=models.CharField(default='Uncategorized', help_text='Specify the category of the blog.', max_length=255),
        ),
    ]
