# Generated by Django 5.1.4 on 2025-01-10 07:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpage_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the category.', max_length=255, unique=True)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Add a short description of the category (optional).')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a category for this blog.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='blog.blogcategory'),
        ),
    ]
