# Generated by Django 5.1.4 on 2025-01-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogcategory_alter_blogpage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='category',
            field=models.CharField(default='Uncategorized', help_text='Specify the category of the blog.', max_length=255),
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
