# Generated by Django 5.1.4 on 2025-01-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
