# Generated by Django 5.1.4 on 2025-01-07 07:47

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('country', models.CharField(help_text='Specify the country for the scholarship.', max_length=255)),
                ('about', wagtail.fields.RichTextField(blank=True, help_text='Provide details about the scholarship.')),
                ('types_of_scholarship', wagtail.fields.RichTextField(blank=True, help_text='Describe the types of scholarships available.')),
                ('how_to_apply', wagtail.fields.RichTextField(blank=True, help_text='Explain the process to apply for the scholarship.')),
                ('tips', wagtail.fields.RichTextField(blank=True, help_text='Provide tips for applying for scholarships.')),
            ],
            options={
                'verbose_name': 'Scholarship Page',
                'verbose_name_plural': 'Scholarship Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ScholarshipDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('government', 'Government'), ('college', 'College'), ('independent', 'Independent')], help_text='Specify the type of provider.', max_length=50)),
                ('grant', models.CharField(help_text='Specify the grant amount or type.', max_length=255)),
                ('deadline', models.DateField(help_text='Enter the deadline for the scholarship.')),
                ('title', models.CharField(help_text='Enter the title of the scholarship.', max_length=255)),
                ('criteria', wagtail.fields.RichTextField(blank=True, help_text='Add eligibility criteria for the scholarship.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_details', to='scholarship.scholarshippage')),
            ],
        ),
    ]
