# Generated by Django 5.1.4 on 2025-01-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blogcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
